name: Deploy FastAPI Project

on:
  push:
    branches:
      - main
# on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - main

jobs:
  deploy:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/aws_key.pem
          chmod 600 ~/.ssh/aws_key.pem
          ssh-keyscan -H 18.191.58.74 >> ~/.ssh/known_hosts

      - name: SSH into AWS VM and deploy
        run: |
          ssh -i ~/.ssh/aws_key.pem ubuntu@18.191.58.74 "cd /home/ubuntu/fastapi-book-project && git pull && sudo systemctl restart fastapi"
